openapi: 3.0.0
info:
  title: EZQurban Ventures
  description: Public API for EZQurban Clients
  version: 1.0.0
servers:
  - url: https://api-ventures.staging.ezqurban.org/v1.0
components:
  securitySchemes:
    apikey:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    Package:
      type: object
      properties:
        id:
          type: integer
          format: int64
        slugId:
          type: string
        name:
          type: string
        sku:
          type: string
        active:
          type: boolean
        description:
          type: string
        pricing:
          type: object
          properties:
            amount:
              type: number
              format: float
            currency:
              type: string
        media:
          type: object
          properties:
            url:
              type: string
            type:
              type: string
            mime:
              type: string
        items:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
              slugId:
                type: string
              sku:
                type: string
              name:
                type: string
              quantity:
                type: integer
                format: int32
    CheckoutItem:
      type: object
      required:
        - productId
        - productQuantity
        - participantName
      properties:
        productId:
          type: integer
          format: int64
        productQuantity:
          type: integer
          format: int32
        participantName:
          type: string
    Buyer:
      type: object
      required:
        - name
        - email
        - phoneNumber
        - identityNumber
      properties:
        name:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        identityNumber:
          type: string
    ShippingAddress:
      type: object
      required:
        - name
        - email
        - phoneNumber
        - addressLine1
        - addressLine2
        - postcode
        - city
        - state
        - country
      properties:
        name:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        postcode:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
    Checkout:
      type: object
      required:
        - items
        - buyer
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CheckoutItem'
        buyer:
          $ref: '#/components/schemas/Buyer'
        shippingAddres:
          $ref: '#/components/schemas/ShippingAddress'
        notes:
          type: string
          

security:
  - apikey: []
tags:
  - name: Packages
  - name: Orders
paths:
  /packages:
    get:
      tags:
        - Packages
      summary: Get Available Packages
      description: Get list of available packages
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Package'
  /orders/checkout:
    post:
      tags:
        - Orders
      summary: Checkout Order
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Checkout'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/confirmed:
    post:
      tags:
        - Orders
      summary: Order Payment Received
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - Orders
      summary: Get Orders
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}:
    get:
      tags:
        - Orders
      summary: Get Order
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}/items/{item-id}:
    get:
      tags:
        - Orders
      summary: Get Order Item
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
        - name: item-id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
