openapi: 3.0.0
info:
  title: EZQurban Ventures
  version: 1.0.0
servers:
  - url: https://api-ventures.staging.ezqurban.org/v1.0
components:
  securitySchemes:
    apikey:
      type: apiKey
      in: header
      name: x-api-key
security:
  - apikey: []
tags:
  - name: Packages
  - name: Orders
paths:
  /packages:
    get:
      tags:
        - Packages
      summary: Get Packages
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/checkout:
    post:
      tags:
        - Orders
      summary: Checkout Order
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/confirmed:
    post:
      tags:
        - Orders
      summary: Order Payment Received
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - Orders
      summary: Get Orders
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}:
    get:
      tags:
        - Orders
      summary: Get Order
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}/items/{item-id}:
    get:
      tags:
        - Orders
      summary: Get Order Item
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
        - name: item-id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
